language: go
go:
- 1.8
script: make test build
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "vBVH30ugG3lFcTPPT8ZOlCnJg83Vcy5dE1J5GNhjdd5MifGi1UMKkv6KM/fKg6E6EFSUFANBv0V2Uh2+l/fC++ex7Sv1tGZ8CjdwM6jSYg5yEUfhSF4SLjBPTcT8P/KxfTE1LF1w+VTnTRbiu0t1X+h4muNuZBqmzBEES8h0hidNGX/kWsKEpz2Uc+uhaX5JE3GJj+0CUrQy5x50L6TpiqH2tX48CzaNQDjHWnMWgamw4hNJ0gwHkrwS1ugULkz5MaBRz1ZGuWUVAyXXgOYLZHSpLp8IAHGuH5K6CbGZtFaLbG+z+BdGi2WZeON+1kKyW2aVbnLt5NTIwD8cznpan98N2qtcTdrZnzU3Tt3BiRI3UeJ9D+nNgsiKXeEe0fuXuHyeJ+DwI0oHimgiKPVwirRLux+4KeF1fU1XGWeAhb5NzCDUTGggy8pV2+gAxcpSXI0P8viniS4XBaj5xh5QTEUpO+1MHZnQJeGsLHkiTNIJ0W5uowsvIY05eVcENWrISQNMyRH+TR2tWlu2flxpNtRN4A/6Eh+t24H5fQF59bS+cIeyCln/5WrWghCANhVbRVq3LXvoRsJWTwkxy7F+F0U6Yv3ijIB8ZNLtQZzSitHaQrXfVbAisy6zhnOkgJijUyjQOKgGBiv5frigYqPaM+ptWQI42zaqrbn4AnFni4E="
  file: check-s3-bucket
  on:
    tags: true
notifications:
  slack:
    secure: CyfbieXN6l/6pdutRh03mck+RVzu39ykBEX3+TXPD7aGMKflukgFUIAMgeP7PHzgnl+S/8ECodLMow8/uHtTJl5s1xRfbSBJOn3VWlw6NCaO2aqAAwX72cZMvUXXTPXSJbDSXuDPPAHp/qQXXw4TzMl+BWnCrRBDXp6dH67Ul+5zUuvMrFd/gsdZL6Y1pa4z06Rg5ojn6so+6nQYgTT6txiSREZ8c8C57c7wZ3CBapeWwMonjI8wrz8BgnOAIqHBXPetRqgPHpavBtniDClId1Qh9Kdy+JjWvMEQEiHL29A0NDvuYmSNvi8BawF4vy+mBUsSzFhiu2bCbHlSqDlo2XHijGeaopvzdu5ih6Nq71MWi+ANaLBRx4pTGXFxiMUiGgLl+/ts+u+LuKA5dKN3hF0FaP/fBnAJe2v6tDhkFxQHCWTNEp68nJ+ADovu3yItngP14lt/qDdNTqATRKX4G4Fl7UECD10J2Wf7PJjw3tnSKLo3fGOUQzlhzgdLf1MVNvYgzkk13yf25VI9h9+QFhbVBqYYQ1r8HsKbhNLY80HebSTdiLB08qpCk+BDJ+39yTZVEBhIeJP8wV5AUAlxEe0rB4yBp2Jo1A5LjR7KPtJ4rVImwqfiUQmlPeY0d8MH8q6YR/xXKVU6C+7tbzdaRqYl7qIB7EvQ+jO7Px0T1IQ=


